### ISSUE TITLE
PDF Generator uses IIIF to properly size page images

### ISSUE THREAD

**Issue by flyingzumwalt** [pulibrary/plum#64] opened 2015-09-10 20:35 UTC
Once IIIF services are available, refactor GeneratesPdfs#to_pdf to use those services.  It should resize the image to fit the page and render it as either a PNG or JPEG.  

Note: You must make sure that images don't exceed the page size.  Default page size is LETTER (612.00 x 792.00).  Currently I'm just telling prawn to make pages with no margins and to limit image height to 792.00.  Ideally this should be replaced by code that uses IIIF to make images that are as close to the page dimensions as possible without exceeding them.

**Comment by tpendragon** [comment] 2015-10-23 16:19
Duplicate of #76

**Closed** 2015-10-23 16:19 UTC
