### ISSUE TITLE
unable to edit scanned resource

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#1097] opened 2017-03-15 14:11 UTC
In Firefox I am currently getting a looooong spin cycle followed by an error message when I try to edit a scanned resource.

**Comment by escowles** [comment] 2017-03-15 14:13
I was just looking at that error in the new error-reporting tool we're trying out (Honey Badger).  It looks like Fedora's not responding, so I'll check that out.

**Comment by escowles** [comment] 2017-03-15 14:16
I didn't see anything obviously wrong with Fedora, but there were a bunch of errors in the logfile that I can dig into.  I restarted Fedora and now I can edit records — can you retry @joycebcat ?

**Comment by joycebcat** [comment] 2017-03-15 14:18
Yep, it just popped right open this time.

**Comment by joycebcat** [comment] 2017-03-15 14:20
Yowzah!!  I edited, saved, and when I clicked "back to search" I got a screen completely full of stuff.  Codes and words and just lots of text but no formatting.

**Comment by jpstroop** [comment] 2017-03-15 14:20
@joycebcat screenshot?

**Comment by joycebcat** [comment] 2017-03-15 14:24
[screenshot PLUM.docx](https://github.com/pulibrary/plum/files/844791/screenshot.PLUM.docx)

**Comment by joycebcat** [comment] 2017-03-15 14:24
Did that work?  Not sure how to attach screenshots in here.

**Comment by joycebcat** [comment] 2017-03-15 14:25
Here is a small snippet from the top of the page down a few lines:

{"response":{"docs":[{"system_create_dtsi":"2017-01-11T20:00:17Z","system_modified_dtsi":"2017-03-15T14:22:25Z","has_model_ssim":["ScannedResource"],"id":"px633g749k","accessControl_ssim":["01881c0e-2306-4b74-82da-ad51eca0ba7f"],"hasRelatedImage_ssim":["pp2678336c"],"depositor_ssim":["tpend"],"depositor_tesim":["tpend"],"title_tesim":["كتاب غاية اتقان الحركات...الخ","Kitāb Ghāyat itqān al-ḥarakāt ... [etc.]"],"date_modified_dtsi":"2017-03-15T14:22:25Z","isPartOf_ssim":["admin_set/default"],"rights_statement_tesim":["http://rightsstatements.org/vocab/NKC/1.0/"],"publisher_tesim":["1917."],"date_created_tesim":["1917-01-01T00:00:00Z"],"subject_tesim":["Astronomy, Arab—Tables","Astronomy, Arab"],"language_tesim":["ara"],"identifier_tesim":["ark:/88435/jm214q43r"],"sort_title_ssim":["K"],"sort_title_tesim":["K"],"replaces_ssim":["pudl0079/ymdi_03_92"],"replaces_tesim":["pudl0079/ymdi_03_92"],"source_metadata_identifier_ssim":["7849451"],"source_metadata_identifier_tesim":["7849451"],"source_jsonld_ssim":["{\"@context\":\"http://bibdata.princeton.edu/context.json\",\"@id\":\"http://bibdata.princeton.edu/bibliographic/7849451\",\"title\":[{\"@value\":\"كتاب غاية اتقان الحركات...الخ\",\"@language\":\"ara\"},{\"@value\":\"Kitāb Ghāyat itqān al-ḥarakāt ... [etc.]\",\"@language\":\"ara-Latn\"}],\"language\":\"ara\",\"call_number\":\"Electronic Resource\",\"extent\":\"235 x 170 (185 x 110 \u0026 205 x 140 \u0026 215 x 155) mm. bound to 240 x 190 mm.\",\"format\":[\"Manuscript\",\"Book\"],\"description\":\"Ownership note, dated June 1926.\",\"publisher\":\"1917.\",\"subje

**Comment by jpstroop** [comment] 2017-03-15 14:27
You can just drop in an image, but this gives us the gist. Thanks.

**Comment by escowles** [comment] 2017-03-15 14:31
I can confirm the "Back to Search" button is linking to the JSON view of the search results — that wall of text is the JSON that Plum gets from Solr and uses to build the search results page.  I've created issue #1098 to fix that.

**Comment by jpstroop** [comment] 2017-03-15 15:22
With #1098 in place I think we can close this?

**Closed** 2017-03-15 15:33 UTC
