### ISSUE TITLE
Character encoding in UV

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#948] opened 2017-01-12 04:01 UTC
Assuming this is a font problem and not a character encoding problem:

<img width="1311" alt="screen shot 2017-01-11 at 10 58 50 pm" src="https://cloud.githubusercontent.com/assets/999701/21876537/bc7d86aa-d851-11e6-9c2d-30222485fdef.png">

Here's the item:
https://plum.princeton.edu/concern/scanned_resources/p0c484h74c

**Comment by tpendragon** [comment] 2017-05-02 19:24
Closed as a duplicate of #1122.

**Comment by tpendragon** [comment] 2017-05-02 19:27
Closed as a duplicate of #1122

**Closed by tpendragon** 2017-05-02 19:27 UTC
