### ISSUE TITLE
Can't update page order

### ISSUE THREAD

**Issue by flyingzumwalt** [pulibrary/plum#56] opened 2015-09-09 01:23 UTC
In order for #9 to be complete, someone has to address projecthydra-labs/activefedora-aggregation#71

**Comment by flyingzumwalt** [comment] 2015-09-09 01:23
FYI @terrellt @jpstroop

**Comment by flyingzumwalt** [comment] 2015-09-09 01:50
Based on a comment by @jcoyne, it might not be possible to avoid loading all of the member objects.  That means you have to load **every page** in a book in order to update the page order within the book.

**Comment by terrellt** [comment] 2015-09-09 02:09
It strikes me that the most efficient method may be to update the proxies and keep track of neighbors on movement, making the max number of updates 6. The danger is a bug causing a break in the links.

**Comment by jpstroop** [comment] 2015-10-07 12:30
Duplicate of #9 ?

**Closed** 2015-11-13 19:39 UTC
Labels: blocked, bug
