### ISSUE TITLE
Arabic CSS problem

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1075] opened 2017-03-08 19:14 UTC
E.g. here: https://plum.princeton.edu/catalog?f%5Bhuman_readable_type_sim%5D%5B%5D=Scanned+Resource&locale=en&page=432&q=

![screen shot 2017-03-08 at 2 13 28 pm](https://cloud.githubusercontent.com/assets/999701/23719473/91d7a898-0409-11e7-88d7-584f2509d8f6.png)

**Comment by tpendragon** [comment] 2017-05-02 19:17
Closed as duplicate of #918

**Closed by tpendragon** 2017-05-02 19:17 UTC
