### ISSUE TITLE
Selecting first child in structure editor highlights the parent as well; can't select other children

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#254] opened 2015-12-16 18:34 UTC
Screenshot isn't that helpful, but FWIW, start with nothing selected, then select the first child. You'll see this:

![select_problem](https://cloud.githubusercontent.com/assets/999701/11850142/94fc1764-a3f9-11e5-87dc-991ab8c86dbc.png)

Also, try selecting any other child; you can't--or at least I can't.

**Comment by tpendragon** [comment] 2015-12-16 18:39
@jpstroop You might have to click drag to select other children. The problem is that the parent is equally as selectable as the children, so the events propagate. I tried to fix it and couldn't get anything working - good to keep here though.

**Comment by jpstroop** [comment] 2015-12-16 18:54
:ok_hand:

**Comment by tpendragon** [comment] 2017-04-26 19:44
Closing until reported again from real feedback.

**Closed by tpendragon** 2017-04-26 19:44 UTC
Labels: wontfix
